# Generated by Django 5.0.7 on 2025-04-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldetails',
            old_name='phone_no',
            new_name='ph_no',
        ),
    ]
